version: '3.8'

services:
  app:
    build: .
    container_name: sbiz-asset-app
    ports:
      - "8080:80"
    volumes:
      - ./apps:/var/www/html
    depends_on:
      - db
    networks:
      - sbiz-network

  db:
    image: mariadb:10.1.19
    container_name: sbiz-asset-db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sbiz_asset
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
      # Option 1: Initial Import with Sample Data (Use this for demo purposes)
      - ./data-sample/struucture-with-data-sample.sql:/docker-entrypoint-initdb.d/init.sql
      
      # Option 2: Initial Import with Structure ONLY (Use this for a fresh production setup)
      # - ./data-sample/structure-only.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - sbiz-network

networks:
  sbiz-network:
    driver: bridge
